Feature/sabrinac spectdc dqm
SBNSoftware/sbndqm pull request #34
Opened 2024-02-02 23:02 UTC by SabrinaBrickner

### Description

Adding 1st draft of Timing (SPECTDC) and fcls to DQM.

Requires sbndcode >= v09_81_02

2024-02-05 16:01 UTC, VCLanNguyen requested changes

2024-02-05 16:01 UTC, VCLanNguyen commented on installations/sbn-fd/startOMProd.sh
This might affect ICARUS (?) so should not include this change in the PR

2024-02-05 16:01 UTC, VCLanNguyen commented on fcl/spectdc_online_monitor.fcl
> +//      }
Is this fcl used at all. If not, can be deleted

2024-02-05 16:01 UTC, VCLanNguyen commented on sbndqm/dqmAnalysis/TPC/CMakeLists.txt
Don't include this file in the PR just in case it overwrites what currently on development branch

2024-02-05 16:01 UTC, VCLanNguyen commented on sbndqm/dqmAnalysis/TPC/OfflineAnalysis_module.cc
Don't include this file in the PR just in case it overwrites what currently on development branch

2024-02-05 16:01 UTC, VCLanNguyen commented on sbndqm/dqmAnalysis/Timing/SPECTDCStreamsNoRedis_module.cc
> +//  sbndaq::sendMetric("Channel populated", nch4, "ch4exists", ch4exists, 0, artdaq::MetricMode::LastPoint);
Uncomment this

2024-02-05 16:01 UTC, VCLanNguyen commented on sbndqm/dqmAnalysis/Timing/SPECTDCStreamsNoRedis_module.cc
> +  //std::string groupName = "SPECTDC";
Uncomment this

2024-02-05 16:01 UTC, VCLanNguyen commented on sbndqm/dqmAnalysis/Timing/SPECTDCStreams_module.cc
Okay, I see that there are two different modules with and without sending metrics to Redis.
Better write as a single module, and make it a fcl parameter whether or not to send metrics to Redis

2024-02-05 16:01 UTC, VCLanNguyen commented on ups/CMakeLists.txt
Don't include this file in the PR

2024-02-05 16:01 UTC, VCLanNguyen commented on ups/product_deps
Don't include this file in the PR

2024-02-05 16:07 UTC, VCLanNguyen commented
The SPEC TDC dqm module looks good to me. Some clean up is needed before approving.

- Some changes we don't want: files in sbn-fd, TPC, ups --> either don't include them in the PR or rebase against the latest sbndqm tag

- Do not need two modules dqm modules with and without Redis: Write it as a single module, and use a fcl parameter to decide whether or not to send metrics

- One redundant spec tdc fcl can be deleted.

2024-02-28 22:13 UTC, eyandel approved these changes

2024-02-28 22:14 UTC, VCLanNguyen commented on installations/sbn-fd/startOMProd.sh
@SabrinaBrickner You can delete this file from the PR

2024-02-28 23:51 UTC, VCLanNguyen approved these changes

2024-09-22 17:56 UTC, mvicenzi commented
This PR was already merged into `release/v1_03_00` with https://github.com/SBNSoftware/sbndqm/commit/acde2a03cf195b992acc0f9d17cb73245ec800a2.
Closing to clean up.

2024-09-22 17:56 UTC, closed without merging