Feature/sbnd v1 04 00
SBNSoftware/sbndqm pull request #39
Opened 2024-10-11 16:15 UTC by wjdanswjddl

Description

- updates to SBND DQM analysis modules for all subsystems: TPC, PMT, CRT, Timing, Trigger.
- updated fcls in subdirectories to test the individual modules, and `online_analysis.fcl` in the `installations/sbn-nd` that runs all subsystem streams 
- `sbndqm/dqmanalysis` TPC and CRT subdirectories are now separated in to ICARUS and SBND subdirectories to prevent conflicts with future developments. SBND modules were renamed by appending "SBND" in the module names

Testing details

All updates are specific to SBND, and were tested on online SBND runs.

2024-10-13 01:46 UTC, mvicenzi requested changes
Unfortunately the current code is not compiling properly at ICARUS because we don't have `sbndcode` available. I'm getting an error regarding the following `include` statement coming from both the SBND event display modules:
```
/home/nfs/icarus/DQM_DevAreas/DQM_2024-09-22_MV_testv1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/SBND/OfflineEvdSBND_module.cc:38:10: fatal error: sbndcode/ChannelMaps/TPC/TPCChannelMapService.h: No such file or directory
   38 | #include "sbndcode/ChannelMaps/TPC/TPCChannelMapService.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Even if I comment it out and I leave the `include` to the local channel map service (see below), I get the following link errors:
 ```
 /usr/bin/ld: cannot find -lsbndcode_ChannelMaps_TPC_TPCChannelMapService_service
collect2: error: ld returned 1 exit status
gmake[2]: *** [sbndqm/slf7.x86_64.e26.prof/lib/libsbndqm_dqmAnalysis_TPC_SBND_OfflineEvdSBND_module.so] Error 1
gmake[1]: *** [sbndqm/sbndqm/dqmAnalysis/TPC/SBND/CMakeFiles/sbndqm_dqmAnalysis_TPC_SBND_OfflineEvdSBND_module.dir/all] Error 2
```

If the plan was to switch to using the local channel map service in `sbndqm/Decode/TPC/SBND/ChannelMap`, it seems it's not working properly. The `include` statements and the `CMakeList` files should be changed to point to the local library instead of the one from `sbndcode`.

2024-10-13 01:46 UTC, mvicenzi commented on sbndqm/dqmAnalysis/TPC/SBND/OnlineEvdSBND_module.cc
> +#include "sbndcode/ChannelMaps/TPC/TPCChannelMapService.h"
I'm getting a compilation error from this include statement... we don't have `sbndcode` available at ICARUS.
I suppose the lines got mixed up? You want to include the local channel mapping service, right?

2024-10-13 01:46 UTC, mvicenzi commented on sbndqm/dqmAnalysis/TPC/SBND/OfflineEvdSBND_module.cc
> +#include "sbndcode/ChannelMaps/TPC/TPCChannelMapService.h"
Same compilation error from here.

2024-10-13 01:46 UTC, mvicenzi commented on sbndqm/dqmAnalysis/TPC/SBND/CMakeLists.txt
> +        sbndcode_ChannelMaps_TPC_TPCChannelMapService_service
We can't link to `sbndcode_ChannelMaps_TPC_TPCChannelMapService_service` at ICARUS.
Did you mean to use the local channel mapping service?

2024-10-13 01:46 UTC, mvicenzi commented on sbndqm/dqmAnalysis/TPC/SBND/CMakeLists.txt
> +        sbndcode_ChannelMaps_TPC_TPCChannelMapService_service
Same here. We can't link to `sbndcode_ChannelMaps_TPC_TPCChannelMapService_service` at ICARUS

2024-10-13 01:46 UTC, mvicenzi commented on sbndqm/Decode/TPC/SBND/CMakeLists.txt
> +  sbndcode_ChannelMaps_TPC_TPCChannelMapService_service
`sbndcode_ChannelMaps_TPC_TPCChannelMapService_service` can't be linked at ICARUS

2024-10-13 01:46 UTC, mvicenzi commented on sbndqm/Decode/TPC/SBND/ChannelMap/CMakeLists.txt
> +                           sbndcode_ChannelMaps_TPC_TPCChannelMapService_service
Same here. Can't be linked at ICARUS.

2024-10-14 00:25 UTC, wjdanswjddl commented
@mvicenzi Updated so that the channel map is called from the local sbndqm subdirectory. Renamed scripts to not clash with sbndcode, as we still need sbndcode set up locally for geometry services.

2024-10-15 22:58 UTC, mvicenzi approved these changes
Thank you @wjdanswjddl !
I checked out the new changes and now it builds without issues.
I've also tested it running alongside `sbndaq v1_10_02` and I see no problems.
From the ICARUS side we can proceed to merge this in and tag the release.

I approve!

2024-10-16 13:10 UTC, wesketchum commented
I got an error building:

```
[ 64%] Building CXX object sbndqm/sbndqm/dqmAnalysis/CRT/ICARUS/CMakeFiles/sbndqm_dqmAnalysis_CRT_ICARUS_BernCRTdqm_module.dir/BernCRTdqm_module.cc.o
In file included from /home/sbn/sbndqm_v1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/AnalysisSBND.hh:28,
                 from /home/sbn/sbndqm_v1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/SBND/OfflineEvdSBND_module.cc:35:
/home/sbn/sbndqm_v1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/FFT.hh:5:10: fatal error: fftw3.h: No such file or directory
    5 | #include "fftw3.h"
      |          ^~~~~~~~~
compilation terminated.
In file included from /home/sbn/sbndqm_v1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/AnalysisSBND.hh:28,
                 from /home/sbn/sbndqm_v1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/SBND/OnlineEvdSBND_module.cc:35:
/home/sbn/sbndqm_v1_03_00/srcs/sbndqm/sbndqm/dqmAnalysis/TPC/FFT.hh:5:10: fatal error: fftw3.h: No such file or directory
    5 | #include "fftw3.h"
      |          ^~~~~~~~~
compilation terminated.
```

I just pushed a commit that cleans up the CMakeLists.txt file a little to get it to build for me. (https://github.com/SBNSoftware/sbndqm/pull/39/commits/a2dcc68ceecc4db7e808ffc07e56e6025f4c9f75)

2024-10-18 15:28 UTC, betan009 approved these changes

2024-10-21 12:24 UTC, merged